### PR TITLE
Support fcontext API in Boost 1.61

### PR DESCRIPTION
**Pull request by clehner**
In Boost 1.61, the API for fcontext_t was changed. I made some changes here to get fc to compile on my machine with Boost 1.61. It is a little hacky but it compiles. However, I have not been able to test it properly. I am trying to build graphene/bitshares-2 but that build fails later in the process. As for fc, running `all_tests` shows the following. I have not compared this with what would happen on my machine with Boost < 1.61:

```
$ ./all_tests
Running 35 test cases...
10 assert_exception: Assert Exception
out_len <= out.size():
    {}
    th_a  smaz.cpp:212 smaz_compress
/home/cel/src/bitshares-2/libraries/fc/tests/crypto/rand_test.cpp(24): error: in "fc_crypto/rand_test": check rc > E - sigma && rc < E + sigma has failed
unknown location(0): fatal error: in "fc_network/ntp_test": memory access violation at address: 0x00000000: no mapping at fault address
/home/cel/src/bitshares-2/libraries/fc/tests/network/ntp_test.cpp(9): last checkpoint: "ntp_test" entry.

*** 2 failures are detected in the test module "AllTests"
```

### CODE REVIEW

**Comment by vikramrajkumar** [comment]
I've tested a version of these changes and it will not work. The Boost API changes include changes to behaviour significant enough that a rewrite of portions of fc is necessary for Boost >= 1.61. This seems to be in development here https://github.com/steemit/fc/tree/boost162 but it is unknown in what timeframe it might be accomplished.

For the foreseeable future only Boost 1.60 or less is supported.
